services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/simplelms
      - REDIS_URL=redis://redis:6379/0
      - REDIS_CACHE_URL=redis://redis:6379/1
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=simplelms_logs
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - db
      - redis
      - rabbitmq
      - mongodb

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: simplelms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  mongodb:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  celery-worker:
    build: .
    command: celery -A simplelms worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/simplelms
      - REDIS_URL=redis://redis:6379/0
      - REDIS_CACHE_URL=redis://redis:6379/1
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=simplelms_logs
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - db
      - rabbitmq
      - redis
      - mongodb

  celery-beat:
    build: .
    command: celery -A simplelms beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/simplelms
      - REDIS_URL=redis://redis:6379/0
      - REDIS_CACHE_URL=redis://redis:6379/1
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=simplelms_logs
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - db
      - rabbitmq
      - redis
      - mongodb

  flower:
    build: .
    command: python -m celery -A simplelms flower --address=0.0.0.0 --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_CACHE_URL=redis://redis:6379/1
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=simplelms_logs
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq
      - redis

volumes:
  postgres_data:
  mongo_data:
  redis_data:
