# Generated by Django 5.0 on 2026-06-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_courseprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
